#!/bin/sh
# Writes the program version header from git: the nearest vX.Y.Z tag, the commits since it and
# the commit hash, plus "-dirty" for uncommitted changes (e.g. 0.3.0-14-g6ac8b0c-dirty).
# The file is only rewritten when the version changes, so builds stay incremental.
# Usage: gen_version.sh <output header>

out="$1"
[ -n "$out" ] || { echo "usage: $0 <output header>" >&2; exit 1; }

cd "$(dirname "$0")/.." || exit 1

ver=$(git describe --tags --match 'v[0-9]*' --dirty --always 2>/dev/null)
if [ -z "$ver" ]; then
    # No git (source archive): keep a header someone already generated, else leave it absent.
    exit 0
fi
ver=${ver#v}

line="#define kProgVersion \"$ver\""
if [ -f "$out" ] && grep -qxF "$line" "$out"; then
    exit 0
fi

printf '// Generated by scripts/gen_version.sh, do not edit.\n%s\n' "$line" > "$out"
